### ISSUE TITLE
Enhancement: Use Turbolinks to SPA-ify UX of Page Load?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-todo-list-tutorial#40]
While reading Blake William's (Thouthbot) "How We Replaced React with Phoenix" https://thoughtbot.com/blog/how-we-replaced-react-with-phoenix
I was reminded of [github.com/turbolinks/turbolinks](https://github.com/turbolinks/turbolinks) and [github.com/stimulusjs/stimulus](https://github.com/stimulusjs/stimulus)
I think Turbolinks would be a good addition to this Todo List Tutorial to make the UX more "SPA". 
It's an easy progressive enhancement that means the page does not do a full refresh but rather the DOM gets updated in place by "diffing". 

@SimonLab Thoughts?
This could be a good issue for you to take a look at if you're interested.

**Comment by SimonLab** [comment]
Adding the following section to the Readme:

### 11.4 Add Turbolinks

Add [turbolinks package](https://www.npmjs.com/package/turbolinks) to `/assets/package.json`:

```sh
cd assets && npm install turbolinks --save
```

In `assets/app.js` import turbolinks and start it with:

```js
import Turbolinks from "turbolinks"
Turbolinks.start();
```

However the following waring is displayed on the console:
![image](https://user-images.githubusercontent.com/6057298/83739727-e43b3700-a64d-11ea-8977-dbc347fd2fcd.png)

Moving the script tag which call `app.js` in the layout to the header fix this warning:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Phoenix Todo List</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  <!-- move script to header-->
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <main role="main" class="container">
      <%= @inner_content %>
    </main>
  </body>
</html>
```

**Comment by nelsonic** [comment]
Added by @SimonLab in #42 🚀
