### ISSUE TITLE
✘ [ERROR] Could not resolve "turbolinks"

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-todo-list-tutorial#57]
Run:
```sh
git checkout main
git pull
mix deps.get
mix setup
```

Then:

```
phoenix-todo-list-tutorial % mix phx.server
[info] Running AppWeb.Endpoint with cowboy 2.9.0 at 127.0.0.1:4000 (http)
[info] Access AppWeb.Endpoint at http://localhost:4000
✘ [ERROR] Could not resolve "turbolinks"

    js/app.js:25:23:
      25 │ import Turbolinks from "turbolinks"
         ╵                        ~~~~~~~~~~~~

  You can mark the path "turbolinks" as external to exclude it from the bundle, which will remove this error.

1 error
[watch] build finished, watching for changes...
```

**Comment by LuchoTurtle** [comment]
You need to run `npm install` inside the assets folder.
I can create a PR to clarify this in README.

**Comment by LuchoTurtle** [comment]
@nelsonic created a [PR](https://github.com/dwyl/phoenix-todo-list-tutorial/pull/58) that should help clarify this issue.

**Comment by nelsonic** [comment]
Turbolinks is no longer maintained:

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/194400/206750796-0ef2074b-2e42-41c4-b263-3d1494e4e8f9.png">

Soo ... it's been renamed to `turbo`: https://github.com/hotwired/turbo

https://turbo.hotwired.dev
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/194400/206751008-88af04ab-83ac-4637-b6f1-c79f97e803b9.png">

Installation: https://turbo.hotwired.dev/handbook/installing

**Comment by nelsonic** [comment]
https://www.honeybadger.io/blog/hb-turbolinks-to-turbo/

**Comment by LuchoTurtle** [comment]
I was aware it was no longer maintained. 
I figured since adding this was just a bonus, it wasn't really needed but I can change it, sure.

**Comment by LuchoTurtle** [comment]
Should be fixed with https://github.com/dwyl/phoenix-todo-list-tutorial/pull/58/commits/6eb70f9bfb65e4aef50049d311a0ae0edc52a268
